export const carImageData = [
  { "Porsche 911 GT3 RS": "OB6cORrtyjo" },
  { "Porsche Cayenne": "0s_5oI3j0zE" },
  { "BMW E36": "OB6cORrtyjo" },
  { "BMW M5": "PmrnsF0UADs" },
  { "BMW M3": "cQHx11ku1Dk" },
  { "Mercedes AMG Gt63s": "OIJaw_ZKea4" },
  { "Mercedes AMG C43": "cyuRhbqG5AI" },
  { "Audi R8": "Dhol4s3fS_Y" },
  { "Audi RS6": "McMMWcSLrGQ" },
  { "Audi RS7": "4gSavS9pe1s" },
  { "Nissan R32": "llKgpQ9AOWY" },
  { "Nissan R35": "K6vOdMaYbFc" },
  { "Nissan 370z": "Zh0XtRBHR0E" },
  { "Subaru WRX STI": "m1aYn08phL4" },
  { "Toyota Supra MK4": "oMcGGGFM5J0" },
  { "Toyota Supra MK5": "s1TOxaRnRmY" },
  { "Toyota GR86": "srnb0mnxfxI" },
  { "Toyota AE86": "6KDd9d_AT00" },
  { "Ford Mustang": "c7Gay8ttJS0" },
  { "Ford GT": "WTAHNvndZcA" },
  { "Chevrolet Camaro": "phiAzHp5Nuo" },
  { "Chevrolet Corvette": "SU6MbWxLozY" },
  { "Dodge Challenger": "rcoDRb_2x90" },
  { "Dodge Charger": "pYwCRcXkiGQ" },
  { "Dodge Viper": "xoMBNgunB5Y" },
];
